CREATE TABLE coffee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(32) NOT NULL,
    supplier_id BIGINT NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    sales INTEGER NOT NULL,
    total INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT pk_coffee PRIMARY KEY (id),
    CONSTRAINT fk_coffee_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (id)
);